apiVersion : apps/v1
kind: Deployment
metadata:
  name: "bot-504d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "bot-504d"
  template:
    metadata:
      labels:
        app: "bot-504d"
    spec:
      containers:
        - name: "bot-504d"
          image: "bot1234.azurecr.io/bot"
          ports:
          - containerPort: 80